version: '3.3'

services:
  web:
    build: ./web
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rankcity
      - POSTGRES_PASSWORD=rankcity
      - POSTGRES_DB=rankcity_dev
    ports:
      - 5432:5432

volumes:
  postgres_data:
